[package]
name = "chopper"
version = "0.1.0"
authors = ["David Kushner <root@davidkushner.me>"]

[dependencies]
time = "0.1.37"
nalgebra = "0.12.3"
winit = "0.6.4"
gfx = "0.16"
glutin = "*"
gfx_window_glutin = "*"

