[package]
name = "chopper"
version = "0.1.0"
authors = ["David Kushner <root@davidkushner.me>"]

[dependencies]
time = "0.1.37"
nalgebra = "0.12.3"
vulkano = "0.4.1"
vulkano-shaders = "0.4.1"
vulkano-win = "0.4.1"
winit = "0.6.4"

